name: Get User Inputs
on:
 workflow_dispatch:
jobs:
  get-inputs:
    runs-on: ubuntu-latest

    steps:
    - name: Get User Inputs
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const inputs = {
            name: process.env.INPUT_NAME,
            age: process.env.INPUT_AGE
          };

          console.log(`User inputs: ${JSON.stringify(inputs)}`);
